
-- Modules
require 'core.options'
require 'core.lazy'
require 'core.theme'
require 'plugins.alpha'
require 'plugins.lualine'
require 'plugins.blankline'
require 'plugins.gitsigns'
require 'plugins.nvim-tree'
require 'plugins.bufferline'
require 'plugins.telescope'
require 'plugins.treesitter'
require 'plugins.cmp'
require 'lsp.lspconfig'